name = "§lNewb X §cManyzz §aV2.9"
version = [0, 15, 0]
min_supported_mc_version = [1, 20, 80]
url = "https://devendrn.github.io/newb-shader/"
authors = ["Itzmanyzz","devendrn"]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor", "Stars"]

[description]
# %w = patch warning, %v = version
long = '''
§c%w
§7- Upgrade Minecraft visuals: vibrant colors, realistic lighting, immersive effects
%v
§3https://github.com/IlhamArrizqi/newb-x-manyzz
'''
short = "Upgrade Minecraft visuals: vibrant colors, realistic lighting, immersive effects"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "0d638c6e-c043-4587-b8da-430cf1444077"
module = "6ee241ac-a460-46f4-8fbc-b9aa9d093686"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
Vanilla Clouds
'''

[[subpack]]
define = "SOFT_CLOUDS"
materials = ["Clouds"]
description = '''
Soft Clouds
'''

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "MULTILAYER_CLOUDS"
materials = ["Clouds"]
description = '''
Multilayer Rounded Clouds
'''

[[subpack]]
define = "PERFORMANCE_MODE"
materials = ["RenderChunk","Clouds"]
description = '''
§cPerformance Mode
'''

[[subpack]]
define = "NIGHT_VISION"
materials = ["RenderChunk","Actor"]
description = '''
Night Vision
'''

[[subpack]]
define = "BLACK_AND_WHITE_STYLE"
materials = ["RenderChunk","Clouds","Sky","EndSky","LegacyCubemap","Actor"]
description = '''
Black And White Style
'''

[[subpack]]
define = "NOSTALGIA_STYLE"
materials = ["RenderChunk","Clouds","Sky","EndSky","LegacyCubemap"]
description = '''
Nostalgia Style
'''

[[subpack]]
define = "VIBRANT_STYLE"
materials = ["RenderChunk","Clouds","Sky","EndSky","LegacyCubemap"]
description = '''
§bVibrant Style
'''

[[subpack]]
define = "UNBOUND_STYLE"
materials = ["RenderChunk","Clouds","Sky","EndSky","LegacyCubemap"]
description = '''
Unbound Style
'''

[[subpack]]
define = "SPOOKY_STYLE"
materials = ["RenderChunk","Clouds","Sky","EndSky","LegacyCubemap"]
description = '''
Spooky Style
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
